name: API tests

on: [push]

permissions:
  contents: 'read'
  id-token: 'write'
  issues: 'write' #__This fixed the HttpError: Resource not accessible by integration
  packages: read
  deployments: read
  checks: write
  statuses: write


jobs:
  test:

    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest --junitxml=test_results.xml
      - uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: PYTest                      # Name of the check run which will be created
          path: 'test_results.xml'          # Path to test results (inside artifact .zip)
          reporter: java-junit              # Format of test results